<div id="destaques" class="central">
	<h2>Destaques</h2>
	<div id="tipoProd">
		<label>Tipo: </label>
                <select name="tipoProduto">
                    <option value="0" selected>Selecione</option>
                    <?php 
                        foreach ($this->params["tipos"] as $vlr){
                            echo '<option value="'.$vlr->getId().'" selected>'.$vlr->getTipoProduto().'</option>';
                        }
                    ?>
		</select>
	</div>
	<?php 
            foreach ($this->params["produtos"] as $vlr){ ?>
                
                </a> <a href="#"><div
			onclick="window.open('produto2.html');window.close()" id="produto_<?php $vlr->getId()?>"
			class="produto comFundo">
			<img alt="adiciona produto" src="img/carrinho_peq.png" class="add" /><img
				alt="produto2" src="img/<?php $vlr->getLinkImage()?>" />
			<pre><?php $vlr->getDsProduto()?></pre>
                        <pre><?php $vlr->getPreco()?></pre>
                        <pre><?php $vlr->getTipoProduto()->getTipoProduto()?></pre>
		</div></a>
            <?php }?>
</div>