<div id="destaques" class="central">
	<h2>Destaques</h2>
	<div id="tipoProd">
		<label>Tipo: </label>
                <select name="tipoProduto" onselect="alert(itemSelecionado);">
                    <option value="0" selected>Selecione</option>
                    <?php 
                        $tipo = new TipoProduto();
                        foreach ($this->params["tipos"] as $tipo){
                            echo '<option value="'.$tipo->getId().'">'.$tipo->getTipoProduto().'</option>';
                        }
                    ?>
		</select>
                <pre>filtro:</pre>
                <pre><?php echo filter_input( INPUT_COOKIE, 'tp_prd', FILTER_SANITIZE_SPECIAL_CHARS ); ?></pre>
	</div>
	<?php 
            $produto = new Produto();
            foreach ($this->params["produtos"] as $produto){ ?>
                <div
			onclick="darkerShow();" id="produto_<?php echo $produto->getId();?>"
			class="produto comFundo">
			<img alt="adiciona produto" src="img/carrinho_peq.png" class="add" /><img
				alt="produto2" src="img/produtos/<?php echo $produto->getLinkImage();?>" />
			<pre><?php echo $produto->getDsProduto();?></pre>
                        <pre><?php echo $produto->getPreco();?></pre>
                        
		</div>
            <?php }?>
</div>