<div class="central">
	<h2 id="cadastro">Cadastro</h2>
	<div class="comFundo formulario">
		<form method="GET" action="_top">
			<div>
				<label>Nome: </label><br /> <label>Sobrenome: </label><br /> <label>e-mail:
				</label><br /> <label>senha: </label><br /> <label>Confirme a senha:
				</label><br />
			</div>
			<div>
				<input type="text" name="nome" /><br /> <input type="text"
					name="sobrenome" /><br /> <input type="email" name="email" /><br />
				<input type="password" name="senha" /><br /> <input type="password"
					name="senhaConf" /><br /> <input type="submit" value="enviar" /> <input
					type="reset" value="limpar" />
			</div>
		</form>
	</div>
</div>